os: osx
osx_image: xcode13.1
language: swift
script: xcodebuild clean build test -project Pokedex/Pokedex.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
